# Generated by Django 5.2.10 on 2026-01-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_deletion_requested',
            field=models.DateTimeField(blank=True, help_text='When account deletion was requested (30-day grace period)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_data_collection',
            field=models.BooleanField(default=True, help_text='Allow anonymous usage analytics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Optional name for personalization', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_score_scale',
            field=models.CharField(choices=[('0-6', 'Combined UAS (0-6)'), ('separate', 'Separate Itch & Hive (0-3 each)')], default='0-6', help_text='Preferred score input method', max_length=20),
        ),
    ]
