# Generated by Django 5.2.10 on 2026-01-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="User's age (optional)", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='csu_diagnosis',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], default='', help_text='Whether user has been diagnosed with CSU', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], default='', help_text='How user describes their gender', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether user has completed onboarding'),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_step',
            field=models.PositiveIntegerField(default=0, help_text='Current onboarding step (0 = not started)'),
        ),
    ]
