# Generated by Django - Migration to mark existing users as onboarded

from django.db import migrations


def mark_existing_users_onboarded(apps, schema_editor):
    """Mark all existing users as having completed onboarding."""
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.filter(onboarding_completed=False).update(
        onboarding_completed=True,
        onboarding_step=7
    )


def reverse_mark_existing_users_onboarded(apps, schema_editor):
    """Reverse: reset onboarding status (for rollback)."""
    # We can't know which users were truly onboarded, so don't change anything
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_onboarding_fields'),
    ]

    operations = [
        migrations.RunPython(
            mark_existing_users_onboarded,
            reverse_mark_existing_users_onboarded,
        ),
    ]
