# Generated by Django 5.2.10 on 2026-01-21 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mark_existing_users_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_prescribed_medication',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('prefer_not_to_say', 'Prefer not to say')], default='', help_text='Whether user has been prescribed medication for their condition', max_length=20),
        ),
        migrations.CreateModel(
            name='UserMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_key', models.CharField(blank=True, default='', help_text="Key from COMMON_MEDICATIONS list (e.g., 'fexofenadine')", max_length=50)),
                ('custom_name', models.CharField(blank=True, default='', help_text='User-entered medication name (if not in list)', max_length=100)),
                ('medication_type', models.CharField(choices=[('antihistamine', 'Antihistamine'), ('biologic', 'Biologic / Injectable'), ('other', 'Other')], default='other', help_text='Category of medication', max_length=20)),
                ('dose_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Dose amount (user-reported, not verified)', max_digits=10, null=True)),
                ('dose_unit', models.CharField(blank=True, default='mg', help_text='Dose unit (e.g., mg, ml)', max_length=20)),
                ('frequency_per_day', models.PositiveIntegerField(blank=True, help_text='How many times per day (user-reported)', null=True)),
                ('last_injection_date', models.DateField(blank=True, help_text='Date of last injection (user-reported)', null=True)),
                ('injection_frequency', models.CharField(blank=True, choices=[('every_2_weeks', 'Every 2 weeks'), ('every_4_weeks', 'Every 4 weeks'), ('every_6_weeks', 'Every 6 weeks'), ('every_8_weeks', 'Every 8 weeks'), ('as_needed', 'As needed'), ('other', 'Other schedule')], default='', help_text='Typical injection schedule', max_length=20)),
                ('is_current', models.BooleanField(default=True, help_text='Whether user is currently taking this')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user medication',
                'verbose_name_plural': 'user medications',
                'ordering': ['-is_current', '-updated_at'],
            },
        ),
    ]
