# Generated by Django 5.2.10 on 2026-01-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_treatment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy_consent_date',
            field=models.DateTimeField(blank=True, help_text='When privacy consent was given', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_consent_given',
            field=models.BooleanField(default=False, help_text='User has explicitly consented to data storage and processing'),
        ),
    ]
