# Generated by Django 5.2.10 on 2026-01-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_privacy_consent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth", null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="User's age (calculated from DOB)", null=True),
        ),
    ]
