# Generated by Django 5.2.10 on 2026-01-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_timezone',
            field=models.CharField(default='Europe/London', help_text='IANA timezone string for the user', max_length=50),
        ),
    ]
