# Generated by Django 5.2.11 on 2026-02-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_pause'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_user_id_fc5b76_idx',
            old_name='accounts_pa_user_id_6a1d8b_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_expires_01b447_idx',
            old_name='accounts_pa_expires_c9b9b7_idx',
        ),
        migrations.AddIndex(
            model_name='usermedication',
            index=models.Index(fields=['user', 'is_current'], name='accounts_us_user_id_0061fe_idx'),
        ),
        migrations.AddIndex(
            model_name='usermedication',
            index=models.Index(fields=['user', 'medication_type'], name='accounts_us_user_id_7d1ba6_idx'),
        ),
    ]
