# Generated by Django 5.2.10 on 2026-01-22 22:34

import backups.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=backups.models.backup_upload_path)),
                ('storage_path', models.CharField(blank=True, default='', max_length=500)),
                ('encryption_metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'backup snapshot',
                'verbose_name_plural': 'backup snapshots',
                'db_table': 'backups_snapshot',
                'indexes': [models.Index(fields=['user', 'created_at'], name='backups_sna_user_id_85a499_idx'), models.Index(fields=['status'], name='backups_sna_status_ea52bd_idx')],
            },
        ),
    ]
