# Generated by Django 5.2.10 on 2026-01-22 22:34

import django.db.models.deletion
import reporting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'Excel')], default='pdf', max_length=10)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=reporting.models.export_job_upload_path)),
                ('file_url', models.URLField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('options_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'export job',
                'verbose_name_plural': 'export jobs',
                'db_table': 'reporting_export_job',
                'indexes': [models.Index(fields=['user', 'status'], name='reporting_e_user_id_60bd20_idx'), models.Index(fields=['expires_at'], name='reporting_e_expires_2863ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'Excel')], default='pdf', max_length=10)),
                ('report_type', models.CharField(default='quick', max_length=20)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report schedule',
                'verbose_name_plural': 'report schedules',
                'db_table': 'reporting_report_schedule',
                'indexes': [models.Index(fields=['user', 'is_active'], name='reporting_r_user_id_10a8e8_idx')],
            },
        ),
    ]
