# Generated by Django 5.2.10 on 2026-01-22 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, default='', help_text='Stripe customer ID', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', help_text='Stripe subscription ID', max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, default='', help_text='Stripe price ID for the subscription plan', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('paused', 'Paused')], default='incomplete', help_text='Current subscription status from Stripe', max_length=30)),
                ('current_period_start', models.DateTimeField(blank=True, help_text='Start of current billing period', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End of current billing period', null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Whether subscription will cancel at period end')),
                ('canceled_at', models.DateTimeField(blank=True, help_text='When the subscription was canceled', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
    ]
