# Generated by Django 5.2.10 on 2026-01-22 22:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_gbp', models.DecimalField(decimal_places=2, help_text='Plan price in GBP', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('billing_period', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=20)),
                ('entitlements_json', models.JSONField(blank=True, default=dict, help_text='Entitlements map for this plan')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'subscription plan',
                'verbose_name_plural': 'subscription plans',
                'db_table': 'subscriptions_plan',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='grace_period_end',
            field=models.DateTimeField(blank=True, help_text='End of grace period after failed payment', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, help_text='End of trial period if applicable', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='EntitlementOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitlement_key', models.CharField(max_length=100)),
                ('value', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlement_overrides_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entitlement override',
                'verbose_name_plural': 'entitlement overrides',
                'db_table': 'subscriptions_entitlement_override',
                'indexes': [models.Index(fields=['user', 'entitlement_key'], name='subscriptio_user_id_b4c89e_idx'), models.Index(fields=['expires_at'], name='subscriptio_expires_46f538_idx')],
            },
        ),
    ]
