# Generated by Django 5.2.10 on 2026-01-21 12:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text="Date of the entry (user's local date)")),
                ('score', models.PositiveIntegerField(help_text='Total CSU score for this day', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(42)])),
                ('itch_score', models.PositiveIntegerField(blank=True, help_text='Itch severity: 0=None, 1=Mild, 2=Moderate, 3=Severe', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('hive_count_score', models.PositiveIntegerField(blank=True, help_text='Hive count: 0=None, 1=Mild (<20), 2=Moderate (20-50), 3=Severe (>50)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about the day')),
                ('took_antihistamine', models.BooleanField(default=False, help_text='Whether antihistamine was taken')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'daily entry',
                'verbose_name_plural': 'daily entries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='tracking_da_user_id_88e39f_idx'), models.Index(fields=['user', '-date'], name='tracking_da_user_id_766f5a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_entry')],
            },
        ),
    ]
