# Generated by Django 5.2.10 on 2026-01-22 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='qol_appearance',
            field=models.PositiveIntegerField(blank=True, help_text='Appearance/embarrassment impact: 0=Not at all, 4=Extremely', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='qol_daily_activities',
            field=models.PositiveIntegerField(blank=True, help_text='Daily activities impact: 0=Not at all, 4=Extremely', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='qol_mood',
            field=models.PositiveIntegerField(blank=True, help_text='Mood/emotional impact: 0=Not at all, 4=Extremely', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='qol_sleep',
            field=models.PositiveIntegerField(blank=True, help_text='Sleep impact: 0=Not at all, 4=Extremely', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
