# Generated by Django 5.2.10 on 2026-01-21 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Whether daily reminders are enabled')),
                ('time_of_day', models.TimeField(default='20:00', help_text='Time to send reminder (HH:MM)')),
                ('timezone', models.CharField(default='America/New_York', help_text='IANA timezone string', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reminder preferences',
                'verbose_name_plural': 'reminder preferences',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='Push service endpoint URL', max_length=500)),
                ('p256dh', models.CharField(help_text='User public key for encryption', max_length=100)),
                ('auth', models.CharField(help_text='Auth secret for encryption', max_length=50)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is still valid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'push subscription',
                'verbose_name_plural': 'push subscriptions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_1159a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'endpoint'), name='unique_user_endpoint')],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date the reminder was for')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the reminder was sent')),
                ('success', models.BooleanField(default=True, help_text='Whether the push was successfully sent')),
                ('subscriptions_notified', models.PositiveIntegerField(default=0, help_text='Number of subscriptions that were notified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reminder log',
                'verbose_name_plural': 'reminder logs',
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_reminder')],
            },
        ),
    ]
