# Generated by Django 5.2.10 on 2026-01-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderpreferences',
            name='last_reminder_date',
            field=models.DateField(blank=True, help_text="The date (in user's timezone) for which last reminder was sent", null=True),
        ),
        migrations.AddField(
            model_name='reminderpreferences',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last reminder sent (for spam prevention)', null=True),
        ),
    ]
