# Generated by Django 5.2.11 on 2026-02-19 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_reminder_guard_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['user', 'date'], name='notificatio_user_id_30d389_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_c3933c_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderpreferences',
            index=models.Index(fields=['enabled'], name='notificatio_enabled_2925ec_idx'),
        ),
    ]
