# Generated by Django 5.2.10 on 2026-01-22 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingContactAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('admin', 'Admin')], default='view', max_length=10)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('resource_type', models.CharField(blank=True, default='', max_length=50)),
                ('resource_id', models.CharField(blank=True, default='', max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sharing access',
                'verbose_name_plural': 'sharing access',
                'db_table': 'sharing_contact_access',
                'indexes': [models.Index(fields=['owner_user', 'contact_email'], name='sharing_con_owner_u_e05a39_idx'), models.Index(fields=['access_token'], name='sharing_con_access__10e5f5_idx')],
            },
        ),
    ]
